export enum ActionTypes {
  GET_LIST_USER = 'GET_LIST_USER',
  GET_LIST_USER_SUCCESS = 'GET_LIST_USER_SUCCESS',
  GET_LIST_USER_FAILURE = 'GET_LIST_USER_FAILURE',

  GET_LIST_CATALOG = 'GET_LIST_CATALOG',
  GET_LIST_CATALOG_SUCCESS = 'GET_LIST_CATALOG_SUCCESS',
  GET_LIST_CATALOG_FAILURE = 'GET_LIST_CATALOG_FAILURE',

  GET_LIST_ARTICLE = 'GET_LIST_ARTICLE',
  GET_LIST_ARTICLE_SUCCESS = 'GET_LIST_ARTICLE_SUCCESS',
  GET_LIST_ARTICLE_FAILURE = 'GET_LIST_ARTICLE_FAILURE',
}
