version: "3.5"
services:
  bloggo-service:
    container_name: bloggocontainer
    build: ./bloggo-fe
    volumes:
      - "./bloggo-fe:/usr/src/app"
    ports:
      - "4200:4200"
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
